### ISSUE TITLE
Create Pipeline for Delivery

### ISSUE THREAD

**Issue by mingcyu** [application-stacks/runtime-component-operator#218]
Will create a brand new project for every build with a unique name, would deploy the secret, deploy the bundle, then run the tests

Build image => Bundle Build => Pushing to cluster => Operator SDK is used to create the catalog => Install Catalog

## Starting Point:
Start with pushing the images(unique image of operator and bundle) into the custom project
Then start with bundle command that will install the operator
Can clean the cluster by deleting the project

## Todos:

- [x] Use pull requests to kick off travis/pipeline
- [x] Deploy image and bundle into OCP environment
    - [x] Need login to the docker hub registry in the cluster(using OC) - To avoid rate limits
    - [x] Make file will create image (Make break builds if we have changes, but only master works) - We can test changes as long we put them in a branch since branch can run on travis
    - [x] Need login to the cluster(using OC) to deploy
    - [x] Get deploy command from Artur 
- [x] Kuttl tests need to be executed after deploying the bundle
- [x] Can clean the cluster by deleting the project

## Stretch Goal:

- [ ] Limiting concurrent builds
- [ ] Contingency for the cloud environment to go away
